[package]
description = "Standard library for Dymension with CosmWasm support included"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "dymension-std"
repository = "https://github.com/dymension-labs/dymension-rust/"
version = "0.22.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces", "dymension-std-derive/backtraces"]

[dependencies]
chrono = { version = "0.4.27", default-features = false }
cosmwasm-std = { version = "=1.1.9", features = ["stargate"] }
dymension-std-derive = { version = "0.20.1", path = "../dymension-std-derive" }
prost = { version = "0.12.3", default-features = false, features = [
    "prost-derive",
] }
prost-types = { version = "0.12.3", default-features = false }
schemars = "0.8.8"

# for query
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-cw-value = "0.7.0"
